#! /usr/bin/env python
# encoding: utf-8

def options(self):
  self.load('compiler_cxx')
  self.recurse('test')

def configure(self):
  self.load('compiler_cxx')
  self.env.append_value('CXXFLAGS', ['-O0', '-g', '-std=c++1y', '-Wall'])
  self.recurse('test')

def build(self):
  self.shlib(
    source = [
      'vst/node.cpp',
      'vst/avl_node.cpp',
      'vst/iterator.cpp',
      'vst/range_iterator.cpp',
      'vst/nearest_neighbor_iterator.cpp'
    ],
    target = 'vst',
    vnum   = '0.9.0'
  )
  self.recurse('test')

# vim: set et sta sw=2 ts=2:
